---
- hosts: okd4-services
  remote_user: okdadmin
  become: yes
  tasks:
  - name: install epel-release
    dnf:
      name: epel-release
      state: latest
      update_cache: yes

  - name: update all
    dnf:
      name: '*'
      state: latest
      update_cache: yes

  - name: restart systemctl
    systemd:
      daemon_reexec: yes

  - name: install git
    dnf:
      name: git
      state: latest
      update_cache: yes